const TokenTypes = {
    IDENTIFIER      : 'IDENTIFIER'      ,
    LINE_COMMENT    : 'LINE_COMMENT'    ,
    BLOCK_COMMENT   : 'BLOCK_COMMENT'   ,
    QUOTE           : 'QUOTE'           ,
    CHAR_QUOTE      : 'CHAR_QUOTE'      ,
    NUMBER          : 'NUMBER'          ,
    PLUS            : 'PLUS'            ,
    MINUS           : 'MINUS'           ,
    MULTIPLY        : 'MULTIPLY'        ,
    PERIOD          : 'PERIOD'          ,
    BACKSLASH       : 'BACKSLASH'       ,
    COLON           : 'COLON'           ,
    PERCENT         : 'PERCENT'         ,
    PIPE            : 'PIPE'            ,
    EXCLAMATION     : 'EXCLAMATION'     ,
    QUESTION        : 'QUESTION'        ,
    POUND           : 'POUND'           ,
    AMPERSAND       : 'AMPERSAND'       ,
    SEMI            : 'SEMI'            ,
    COMMA           : 'COMMA'           ,
    L_PAREN         : 'L_PAREN'         ,
    R_PAREN         : 'R_PAREN'         ,
    L_ANG           : 'L_ANG'           ,
    R_ANG           : 'R_ANG'           ,
    L_BRACE         : 'L_BRACE'         ,
    R_BRACE         : 'R_BRACE'         ,
    L_BRACKET       : 'L_BRACKET'       ,
    R_BRACKET       : 'R_BRACKET'       ,
    EQUALS          : 'EQUALS'          ,
    AT              : 'AT'              ,
};

module.exports = TokenTypes;