const TokenTypes = require('./TokenTypes');


module.exports = {
    '+' : TokenTypes.PLUS       ,
    '-' : TokenTypes.MINUS      ,
    '*' : TokenTypes.MULTIPLY   ,
    '/' : TokenTypes.DIVIDE     ,
    '.' : TokenTypes.PERIOD     ,
    '\\': TokenTypes.BACKSLASH  ,
    ':' : TokenTypes.COLON      ,
    '%' : TokenTypes.PERCENT    ,
    '|' : TokenTypes.PIPE       ,
    '!' : TokenTypes.EXCLAMATION,
    '?' : TokenTypes.QUESTION   ,
    '#' : TokenTypes.POUND      ,
    '&' : TokenTypes.AMPERSAND  ,
    ';' : TokenTypes.SEMI       ,
    ',' : TokenTypes.COMMA      ,
    '(' : TokenTypes.L_PAREN    ,
    ')' : TokenTypes.R_PAREN    ,
    '<' : TokenTypes.L_ANG      ,
    '>' : TokenTypes.R_ANG      ,
    '{' : TokenTypes.L_BRACE    ,
    '}' : TokenTypes.R_BRACE    ,
    '[' : TokenTypes.L_BRACKET  ,
    ']' : TokenTypes.R_BRACKET  ,
    '=' : TokenTypes.EQUALS     ,
    '@' : TokenTypes.AT         ,
};